config_version: 2

general_settings:
  enabled: true
  display_name: "Connector"
  # When machine is placed on a block, it will be offset by this vector.
  # This vector is facing the positive Z direction. Rotation will be automatically applied.
  placement_offset: [0, 0, 0]
  # If set to true, structure can be broken only with a hammer.
  heavy: false
  portable_data: [ "flow", "filter" ]

info_hologram:
  offset: [0, 0, 0] # Location of the TextDisplay relative to the structure
  translation: [1.2, 0, 0] # Translation applied to TextDisplay

model_controller:
  type: SINGLEPART
  cases:
    fallback:
      model: "connector.model.yml"