config_version: 2

general_settings:
  enabled: true
  display_name: "Energy Cable"
  # When machine is placed on a block, it will be offset by this vector.
  # This vector is facing the positive Z direction. Rotation will be automatically applied.
  placement_offset: [0, 0, 0]
  # If set to true, structure can be broken only with a hammer.
  heavy: false
  portable_data: []

model_controller:
  type: MULTIPART
  cases:
    fallback:
      model: "energy_cable_not_connected.model.yml"
    state[north=true]:
      model: "energy_cable_north.model.yml"
    state[east=true]:
      model: "energy_cable_east.model.yml"
    state[south=true]:
      model: "energy_cable_south.model.yml"
    state[west=true]:
      model: "energy_cable_west.model.yml"
    state[up=true]:
      model: "energy_cable_up.model.yml"
    state[down=true]:
      model: "energy_cable_down.model.yml"