config_version: 2

general_settings:
  enabled: true
  display_name: "Junction Box"
  # When machine is placed on a block, it will be offset by this vector.
  # This vector is facing the positive Z direction. Rotation will be automatically applied.
  placement_offset: [0, 0, 0]
  # If set to true, structure can be broken only with a hammer.
  heavy: false
  portable_data: []

info_hologram:
  offset: [0, 0, 0] # Location of the TextDisplay relative to the structure
  translation: [1.4, 0.1, 0] # Translation applied to TextDisplay

model_controller:
  type: MULTIPART
  cases:
    fallback:
      model: "junction_box_base.model.yml"
    state[right=true]:
      model: "energy_cable_east.model.yml"
    state[back=true]:
      model: "energy_cable_south.model.yml"
    state[left=true]:
      model: "energy_cable_west.model.yml"
    state[up=true]:
      model: "energy_cable_up.model.yml"
    state[down=true]:
      model: "energy_cable_down.model.yml"