general_settings:
  enabled: true
  display_name: "Quarry"
  # When machine is placed on a block, it will be offset by this vector.
  # This vector is facing the positive Z direction. Rotation will be automatically applied.
  placement_offset: [0, 0, -6]
  # If set to true, structure can be broken only with a hammer.
  heavy: true
  portable_data: [ "energy" ]

energy_settings:
  consumption_on_move: 30
  consumption_on_mine: 50
  capacity: 2000 # (default: 2000)
  maximum_input: 350 # (default: 350)

special_settings:
  maximum_depth: 64 # (default: 64)

info_hologram:
  offset: [0, 0, -6] # Location of the TextDisplay relative to the structure
  translation: [1.2, 0, 0] # Translation applied to TextDisplay

model_controller:
  type: SINGLEPART
  cases:
    fallback:
      model: "quarry.model.yml"