type: MULTIPART
cases:
  fallback:
    model: "connector_socket"
  state[front=true]:
    model: "generic_cable_north"
    variables:
      material: light_gray_terracotta
  state[right=true]:
    model: "generic_cable_east"
    variables:
      material: light_gray_terracotta
  state[back=true]:
    model: "generic_cable_south"
    variables:
      material: light_gray_terracotta
  state[left=true]:
    model: "generic_cable_west"
    variables:
      material: light_gray_terracotta
  state[up=true]:
    model: "generic_cable_up"
    variables:
      material: light_gray_terracotta
  state[down=true]:
    model: "generic_cable_down"
    variables:
      material: light_gray_terracotta