type: MULTIPART
cases:
  fallback:
    model: "energy_cable_not_connected"
  state[north=true]:
    model: "energy_cable_north"
  state[east=true]:
    model: "energy_cable_east"
  state[south=true]:
    model: "energy_cable_south"
  state[west=true]:
    model: "energy_cable_west"
  state[up=true]:
    model: "energy_cable_up"
  state[down=true]:
    model: "energy_cable_down"