type: MULTIPART
cases:
  fallback:
    model: "generic_pipe_not_connected"
    variables:
      material: light_blue_terracotta
  state[north=true]:
    model: "generic_pipe_north"
    variables:
      material: light_blue_terracotta
  state[east=true]:
    model: "generic_pipe_east"
    variables:
      material: light_blue_terracotta
  state[south=true]:
    model: "generic_pipe_south"
    variables:
      material: light_blue_terracotta
  state[west=true]:
    model: "generic_pipe_west"
    variables:
      material: light_blue_terracotta
  state[up=true]:
    model: "generic_pipe_up"
    variables:
      material: light_blue_terracotta
  state[down=true]:
    model: "generic_pipe_down"
    variables:
      material: light_blue_terracotta