type: MULTIPART
cases:
  fallback:
    model: "generic_cable_not_connected"
    variables:
      material: light_gray_terracotta
  state[north=true]:
    model: "generic_cable_north"
    variables:
      material: light_gray_terracotta
  state[east=true]:
    model: "generic_cable_east"
    variables:
      material: light_gray_terracotta
  state[south=true]:
    model: "generic_cable_south"
    variables:
      material: light_gray_terracotta
  state[west=true]:
    model: "generic_cable_west"
    variables:
      material: light_gray_terracotta
  state[up=true]:
    model: "generic_cable_up"
    variables:
      material: light_gray_terracotta
  state[down=true]:
    model: "generic_cable_down"
    variables:
      material: light_gray_terracotta