type: MULTIPART
cases:
  fallback:
    model: "junction_box_base"
  state[right=true]:
    model: "generic_cable_east"
    variables:
      material: gray_wool
  state[back=true]:
    model: "generic_cable_south"
    variables:
      material: gray_wool
  state[left=true]:
    model: "generic_cable_west"
    variables:
      material: gray_wool
  state[up=true]:
    model: "generic_cable_up"
    variables:
      material: gray_wool
  state[down=true]:
    model: "generic_cable_down"
    variables:
      material: gray_wool