general_settings:
  enabled: true
  display_name: "Fluid Tank"
  # When machine is placed on a block, it will be offset by this vector.
  # This vector is facing the positive Z direction. Rotation will be automatically applied.
  placement_offset: [0, 0, 0]
  # If set to true, structure can be broken only with a hammer.
  heavy: true
  portable_data: [ "fluid", "stored" ]

fluid_settings:
  capacity: 96000

info_hologram:
  offset: [0, 1, 0] # Location of the TextDisplay relative to the structure
  translation: [2, 0, 1] # Translation applied to TextDisplay